name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-14"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmYzZTZjN2MtODhmYy00MGJmLThmN2UtYzYyNGNlOTU5MGE0IiwidGVuYW50X2lkIjoiNjRlYmZlYWEyMmYyZTFjNzJiY2Y1NzVkMzkwZmYxMDMxZjI5MTMxZDY5MjBmMzM4ZmZkZDNhNTc2ZjU3Nzk3NCIsImludGVybmFsX3NlY3JldCI6ImNmM2FjZjc0LTJjNGEtNDJiZi05MWM0LTUwMmQyMTg3N2Y0ZSJ9.tpqBlUgdGGBDEAgO_wCMGwBEEb37Y9JsLWL__9IyIVo"

JWT_SECRET = "secretToken"